service: cvs-svc-document-retrieval

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    lambda: true
    apiGateway: true
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

plugins:
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-typescript

functions:
  handler:
    handler: src/handler.handler
    events:
      - http:
          path: document-retrieval
          method: get

custom:
  serverless-offline:
    port: 3013
    stages:
      - dev