openapi: 3.0.0
info:
  version: 1.0.0
  title: Document Retrieval API
paths:
  /:
    get:
      summary: Debug Route
      responses:
        '200':
          description: OK

  /version:
    get:
      summary: Get API Version
      responses:
        '200':
          description: OK

  /document-retrieval:
    get:
      summary: Retrieve a Document
      parameters:
        - name: vinNumber
          in: query
          description: VIN number
          required: false
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]*$'
        - name: testNumber
          in: query
          description: Test number
          required: false
          schema:
            type: string
            pattern: '^[a-zA-Z]\d{2}[a-zA-Z]\d{5}$'
        - name: plateSerialNumber
          in: query
          description: Plate serial number
          required: false
          schema:
            type: string
            pattern: '/^plate_[0-9]{1,12}$/'
        - name: systemNumber
          in: query
          description: System number
          required: false
          schema:
            type: string
        - name: fileName
          in: query
          description: Name of the file to retrieve
          required: false
          schema:
            type: string
        - name: adrDocumentId
          in: query
          description: ADR Document ID
          required: false
          schema:
            type: string

      responses:
        '200':
          description: Document Retrieved Successfully
          content:
            application/pdf:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Bad request
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Internal server error

  /getCertificate:
    get:
      summary: Get a Certificate
      parameters:
        - name: vinNumber
          in: query
          description: VIN number
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]*$'
        - name: testNumber
          in: query
          description: Test number
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]\d{2}[a-zA-Z]\d{5}$'
      responses:
        '200':
          description: Certificate Retrieved Successfully
          content:
            application/pdf:
              schema:
                type: string
  /getLetter:
    get:
      summary: Get a Letter
      parameters:
        - name: vinNumber
          in: query
          description: VIN number
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]*$'
        - name: systemNumber
          in: query
          description: System number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Letter Retrieved Successfully
          content:
            application/pdf:
              schema:
                type: string
  /getPlate:
    get:
      summary: Get a Plate
      parameters:
        - name: plateSerialNumber
          in: query
          description: Plate serial number
          required: true
          schema:
            type: string
            pattern: '/^plate_[0-9]{1,12}$/'
      responses:
        '200':
          description: Plate Retrieved Successfully
          content:
            application/pdf:
              schema:
                type: string
